//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon_Type()
        {
            this.Bon_Destruction = new HashSet<Bon_Destruction>();
            this.Bon_Entree = new HashSet<Bon_Entree>();
            this.Bon_Sortie = new HashSet<Bon_Sortie>();
            this.Operation_Bon_Entree_Magasin = new HashSet<Operation_Bon_Entree_Magasin>();
            this.Operation_Bon_Sortie_Magasin = new HashSet<Operation_Bon_Sortie_Magasin>();
        }
    
        public decimal bon_T_ID { get; set; }
        public string bon_T_Code { get; set; }
        public string bon_T_Type { get; set; }
        public Nullable<bool> bon_T_Status { get; set; }
        public string bon_T_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Destruction> Bon_Destruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree> Bon_Entree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie> Bon_Sortie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Bon_Entree_Magasin> Operation_Bon_Entree_Magasin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Bon_Sortie_Magasin> Operation_Bon_Sortie_Magasin { get; set; }
    }
}
