//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Destruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bon_Destruction()
        {
            this.Bon_Destruction_Produit = new HashSet<Bon_Destruction_Produit>();
        }
    
        public decimal bon_D_ID { get; set; }
        public string bon_D_Code { get; set; }
        public Nullable<System.DateTime> bon_D_Date { get; set; }
        public Nullable<System.TimeSpan> bon_D_Temps { get; set; }
        public string bon_D_Text { get; set; }
        public Nullable<bool> bon_D_Status { get; set; }
        public string bon_D_Note { get; set; }
        public Nullable<decimal> fact_ID { get; set; }
        public Nullable<decimal> bon_T_ID { get; set; }
    
        public virtual Bon_Type Bon_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Destruction_Produit> Bon_Destruction_Produit { get; set; }
    }
}
