//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Destruction_Produit
    {
        public decimal prd_B_D_ID { get; set; }
        public string prd_B_D_Code { get; set; }
        public Nullable<System.DateTime> prd_B_D_Date { get; set; }
        public Nullable<System.TimeSpan> prd_B_D_Temps { get; set; }
        public Nullable<int> prd_B_D_Quantite { get; set; }
        public string prd_B_D_Text { get; set; }
        public Nullable<bool> prd_B_D_Status { get; set; }
        public string prd_B_D_Note { get; set; }
        public Nullable<decimal> prd_ID { get; set; }
        public Nullable<decimal> bon_D_ID { get; set; }
    
        public virtual Bon_Destruction Bon_Destruction { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
