//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Charge()
        {
            this.Compte_Charge = new HashSet<Compte_Charge>();
        }
    
        public decimal chg_ID { get; set; }
        public string chg_Code { get; set; }
        public string chg_Nom { get; set; }
        public Nullable<decimal> chg_Max_Valeur { get; set; }
        public Nullable<bool> chg_Status { get; set; }
        public string chg_Note { get; set; }
        public Nullable<decimal> chg_T_ID { get; set; }
    
        public virtual Charge_Type Charge_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Charge> Compte_Charge { get; set; }
    }
}
