//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Compte_Client = new HashSet<Compte_Client>();
            this.Facture_Vente = new HashSet<Facture_Vente>();
            this.Facture_Vente_Retour = new HashSet<Facture_Vente_Retour>();
            this.Operation_Facture_Vente = new HashSet<Operation_Facture_Vente>();
            this.Operation_Facture_Vente_Retour = new HashSet<Operation_Facture_Vente_Retour>();
        }
    
        public decimal clt_ID { get; set; }
        public string clt_Code { get; set; }
        public string clt_Nom { get; set; }
        public Nullable<System.DateTime> clt_Date { get; set; }
        public string clt_Nature { get; set; }
        public string clt_Adresse { get; set; }
        public string clt_Tele { get; set; }
        public string clt_Tele2 { get; set; }
        public string clt_Tax_Num { get; set; }
        public Nullable<bool> clt_Status { get; set; }
        public string clt_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Client> Compte_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente> Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Retour> Facture_Vente_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente> Operation_Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente_Retour> Operation_Facture_Vente_Retour { get; set; }
    }
}
