//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte_Charge
    {
        public decimal chg_C_ID { get; set; }
        public string chg_C_Code { get; set; }
        public string chg_C_Nom { get; set; }
        public Nullable<System.DateTime> chg_C_Date { get; set; }
        public Nullable<bool> chg_C_Status { get; set; }
        public string chg_C_Note { get; set; }
        public Nullable<decimal> chg_ID { get; set; }
    
        public virtual Charge Charge { get; set; }
    }
}
