//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devise_Banque
    {
        public decimal dvs_B_ID { get; set; }
        public string dvs_B_Code { get; set; }
        public string dvs_B_Nom { get; set; }
        public Nullable<bool> dvs_B_Status { get; set; }
        public Nullable<decimal> ban_ID { get; set; }
        public Nullable<decimal> dvs_ID { get; set; }
    
        public virtual Banque Banque { get; set; }
        public virtual Devise Devise { get; set; }
    }
}
