//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Compte_Employee = new HashSet<Compte_Employee>();
            this.Employee_Salaire = new HashSet<Employee_Salaire>();
        }
    
        public decimal empl_ID { get; set; }
        public string empl_Code { get; set; }
        public string empl_Nom { get; set; }
        public string empl_Prenom { get; set; }
        public string empl_Type { get; set; }
        public Nullable<decimal> empl_Salaire { get; set; }
        public Nullable<int> empl_Heure_Travail { get; set; }
        public Nullable<System.DateTime> empl_Date_Eumbauche { get; set; }
        public string empl_Adresse { get; set; }
        public string empl_Tele { get; set; }
        public string empl_Position_Travail { get; set; }
        public Nullable<decimal> barn_ID { get; set; }
        public Nullable<bool> empl_Status { get; set; }
        public string empl_Note { get; set; }
    
        public virtual Branche Branche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Employee> Compte_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Salaire> Employee_Salaire { get; set; }
    }
}
