//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entreprise_Info()
        {
            this.Branches = new HashSet<Branche>();
        }
    
        public decimal entr_ID { get; set; }
        public string entr_Code { get; set; }
        public string entr_Nom { get; set; }
        public string entr_Adresse1 { get; set; }
        public string entr_Adresse2 { get; set; }
        public string entr_Mobile1 { get; set; }
        public string entr_Mobile2 { get; set; }
        public string entr_Fixe1 { get; set; }
        public string entr_Fixe2 { get; set; }
        public string entr_Fax1 { get; set; }
        public string entr_Fax2 { get; set; }
        public string entr_Email { get; set; }
        public byte[] entr_Image { get; set; }
        public string entr_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branche> Branches { get; set; }
    }
}
