//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Achat_Produit
    {
        public decimal fact_A_P_ID { get; set; }
        public string fact_A_P_Code { get; set; }
        public Nullable<System.DateTime> fact_A_P_Date { get; set; }
        public Nullable<System.TimeSpan> fact_A_P_Temps { get; set; }
        public string fact_A_P_Text { get; set; }
        public Nullable<decimal> fact_A_P_Prix { get; set; }
        public Nullable<decimal> fact_A_P_Prix_Vente { get; set; }
        public Nullable<decimal> fact_A_P_Remise { get; set; }
        public Nullable<bool> fact_A_P_Remise_Type { get; set; }
        public Nullable<decimal> fact_A_P_Total { get; set; }
        public Nullable<int> fact_A_P_Quantite { get; set; }
        public Nullable<decimal> prd_ID { get; set; }
        public Nullable<decimal> unt_M_ID { get; set; }
        public Nullable<decimal> unt_T_ID { get; set; }
        public Nullable<bool> fact_A_P_Status { get; set; }
        public string fact_A_P_Note { get; set; }
        public Nullable<decimal> fact_A_ID { get; set; }
    
        public virtual Facture_Achat Facture_Achat { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        public virtual Unite_Type Unite_Type { get; set; }
    }
}
