//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Vente_Retour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture_Vente_Retour()
        {
            this.Facture_Vente_Produit_Retour = new HashSet<Facture_Vente_Produit_Retour>();
            this.Operation_Facture_Vente_Retour = new HashSet<Operation_Facture_Vente_Retour>();
        }
    
        public decimal fact_V_R_ID { get; set; }
        public string fact_V_R_Code { get; set; }
        public Nullable<System.DateTime> fact_V_R_Date { get; set; }
        public Nullable<System.TimeSpan> fact_V_R_Temps { get; set; }
        public Nullable<System.DateTime> fact_V_R_Ech_Date { get; set; }
        public string fact_V_R_Text { get; set; }
        public Nullable<decimal> clt_ID { get; set; }
        public Nullable<decimal> fact_V_R_Montatnt { get; set; }
        public Nullable<decimal> fact_V_R_Tax_Pourc { get; set; }
        public Nullable<decimal> fact_V_R_Tax_Montant { get; set; }
        public Nullable<decimal> fact_V_R_Tax_Montant_Apres { get; set; }
        public Nullable<decimal> fact_V_R_Escompte { get; set; }
        public Nullable<decimal> fact_V_R_Escompte_Type { get; set; }
        public Nullable<decimal> fact_V_R_Total { get; set; }
        public Nullable<decimal> fact_V_R_Net { get; set; }
        public string fact_V_R_Adresse { get; set; }
        public Nullable<decimal> pay_ID { get; set; }
        public Nullable<decimal> fact_T_ID { get; set; }
        public Nullable<bool> fact_V_R_Status { get; set; }
        public string fact_V_R_Note { get; set; }
        public Nullable<decimal> fact_V_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Facture_Paiement_Type Facture_Paiement_Type { get; set; }
        public virtual Facture_Type Facture_Type { get; set; }
        public virtual Facture_Vente Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Produit_Retour> Facture_Vente_Produit_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente_Retour> Operation_Facture_Vente_Retour { get; set; }
    }
}
