//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Vente_Bonus
    {
        public decimal fact_V_B_ID { get; set; }
        public string fact_V_B_Code { get; set; }
        public Nullable<System.DateTime> fact_V_B_Date { get; set; }
        public Nullable<System.TimeSpan> fact_V_B_Temps { get; set; }
        public string fact_V_B_Text { get; set; }
        public Nullable<int> fact_V_B_Quantite { get; set; }
        public Nullable<decimal> prd_ID { get; set; }
        public Nullable<decimal> unt_M_ID { get; set; }
        public Nullable<decimal> unt_T_ID { get; set; }
        public Nullable<bool> fact_V_B_Status { get; set; }
        public string fact_V_B_Note { get; set; }
        public Nullable<decimal> fact_V_ID { get; set; }
    
        public virtual Facture_Vente Facture_Vente { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        public virtual Unite_Type Unite_Type { get; set; }
    }
}
