//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Achat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture_Achat()
        {
            this.Bon_Entree = new HashSet<Bon_Entree>();
            this.Facture_Achat_Bonus = new HashSet<Facture_Achat_Bonus>();
            this.Facture_Achat_Produit = new HashSet<Facture_Achat_Produit>();
            this.Facture_Achat_Retour = new HashSet<Facture_Achat_Retour>();
            this.Operation_Facture_Achat = new HashSet<Operation_Facture_Achat>();
            this.Recu_Achat = new HashSet<Recu_Achat>();
        }
    
        public decimal fact_A_ID { get; set; }
        public string fact_A_Code { get; set; }
        public Nullable<System.DateTime> fact_A_Date { get; set; }
        public Nullable<System.TimeSpan> fact_A_Temps { get; set; }
        public Nullable<System.DateTime> fact_A_Ech_Date { get; set; }
        public string fact_A_Text { get; set; }
        public Nullable<decimal> frns_ID { get; set; }
        public Nullable<decimal> fact_A_Montatnt { get; set; }
        public Nullable<decimal> fact_A_Tax_Pourc { get; set; }
        public Nullable<decimal> fact_A_Tax_Montant { get; set; }
        public Nullable<decimal> fact_A_Tax_Montant_Apres { get; set; }
        public Nullable<decimal> fact_A_Escompte { get; set; }
        public Nullable<decimal> fact_A_Escompte_Type { get; set; }
        public Nullable<decimal> fact_A_Total { get; set; }
        public Nullable<decimal> fact_A_Net { get; set; }
        public string fact_A_Adresse { get; set; }
        public Nullable<decimal> pay_ID { get; set; }
        public Nullable<decimal> fact_T_ID { get; set; }
        public Nullable<bool> fact_A_Status { get; set; }
        public string fact_A_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree> Bon_Entree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Bonus> Facture_Achat_Bonus { get; set; }
        public virtual Facture_Paiement_Type Facture_Paiement_Type { get; set; }
        public virtual Facture_Type Facture_Type { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Produit> Facture_Achat_Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Retour> Facture_Achat_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Achat> Operation_Facture_Achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recu_Achat> Recu_Achat { get; set; }
    }
}
