//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture_Vente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture_Vente()
        {
            this.Bon_Sortie = new HashSet<Bon_Sortie>();
            this.Facture_Vente_Bonus = new HashSet<Facture_Vente_Bonus>();
            this.Facture_Vente_Produit = new HashSet<Facture_Vente_Produit>();
            this.Facture_Vente_Retour = new HashSet<Facture_Vente_Retour>();
            this.Operation_Facture_Vente = new HashSet<Operation_Facture_Vente>();
            this.Recu_Vente = new HashSet<Recu_Vente>();
        }
    
        public decimal fact_V_ID { get; set; }
        public string fact_V_Code { get; set; }
        public Nullable<System.DateTime> fact_V_Date { get; set; }
        public Nullable<System.TimeSpan> fact_V_Temps { get; set; }
        public Nullable<System.DateTime> fact_V_Ech_Date { get; set; }
        public string fact_V_Text { get; set; }
        public Nullable<decimal> clt_ID { get; set; }
        public Nullable<decimal> fact_V_Montatnt { get; set; }
        public Nullable<decimal> fact_V_Tax_Pourc { get; set; }
        public Nullable<decimal> fact_V_Tax_Montant { get; set; }
        public Nullable<decimal> fact_V_Tax_Montant_Apres { get; set; }
        public Nullable<decimal> fact_V_Escompte { get; set; }
        public Nullable<decimal> fact_V_Escompte_Type { get; set; }
        public Nullable<decimal> fact_V_Total { get; set; }
        public Nullable<decimal> fact_V_Net { get; set; }
        public string fact_V_Adresse { get; set; }
        public Nullable<decimal> pay_ID { get; set; }
        public Nullable<decimal> fact_T_ID { get; set; }
        public Nullable<bool> fact_V_Status { get; set; }
        public string fact_V_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie> Bon_Sortie { get; set; }
        public virtual Client Client { get; set; }
        public virtual Facture_Paiement_Type Facture_Paiement_Type { get; set; }
        public virtual Facture_Type Facture_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Bonus> Facture_Vente_Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Produit> Facture_Vente_Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Retour> Facture_Vente_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Facture_Vente> Operation_Facture_Vente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recu_Vente> Recu_Vente { get; set; }
    }
}
