//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impot()
        {
            this.Operation_Impot = new HashSet<Operation_Impot>();
        }
    
        public decimal imp_ID { get; set; }
        public string imp_Code { get; set; }
        public Nullable<System.DateTime> imp_Date { get; set; }
        public string imp_Nom { get; set; }
        public Nullable<decimal> imp_Montant { get; set; }
        public Nullable<int> imp_Pourcentage { get; set; }
        public Nullable<bool> imp_Status { get; set; }
        public string imp_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Impot> Operation_Impot { get; set; }
    }
}
