//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin_Branche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin_Branche()
        {
            this.Produit_Emplacement = new HashSet<Produit_Emplacement>();
        }
    
        public decimal mgs_Branche_ID { get; set; }
        public string mgs_Branche_Code { get; set; }
        public Nullable<System.DateTime> mgs_Branche_Date { get; set; }
        public Nullable<bool> mgs_Branche_Status { get; set; }
        public Nullable<decimal> barn_ID { get; set; }
        public Nullable<decimal> mags_ID { get; set; }
        public string mgs_Branche_Note { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Magasin Magasin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit_Emplacement> Produit_Emplacement { get; set; }
    }
}
