//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magasin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magasin()
        {
            this.Magasin_Branche = new HashSet<Magasin_Branche>();
        }
    
        public decimal mags_ID { get; set; }
        public string mags_Code { get; set; }
        public string mags_Nom { get; set; }
        public Nullable<System.DateTime> mags_Date { get; set; }
        public string mags_Emplacement { get; set; }
        public string mags_Type { get; set; }
        public string mags_Tele { get; set; }
        public string mags_Fax { get; set; }
        public Nullable<bool> mags_Status { get; set; }
        public string mags_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magasin_Branche> Magasin_Branche { get; set; }
    }
}
