//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Caisse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main_Caisse()
        {
            this.Compte_Bancaire = new HashSet<Compte_Bancaire>();
            this.Compte_Espece = new HashSet<Compte_Espece>();
            this.Operation_Caisse = new HashSet<Operation_Caisse>();
        }
    
        public decimal cais_ID { get; set; }
        public string cais_Code { get; set; }
        public Nullable<System.DateTime> cais_Date_Creation { get; set; }
        public Nullable<decimal> cais_D_Solde { get; set; }
        public Nullable<decimal> cais_Z_Solde { get; set; }
        public Nullable<decimal> cais_Solde { get; set; }
        public Nullable<int> cais_Status { get; set; }
        public string cais_Note { get; set; }
        public Nullable<decimal> barn_ID { get; set; }
    
        public virtual Branche Branche { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Bancaire> Compte_Bancaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compte_Espece> Compte_Espece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation_Caisse> Operation_Caisse { get; set; }
    }
}
