//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Facture_Vente_Retour
    {
        public decimal fact_V_R_O_ID { get; set; }
        public string fact_V_R_O_Code { get; set; }
        public Nullable<System.DateTime> fact_V_R_O_Date { get; set; }
        public Nullable<System.TimeSpan> fact_V_R_O_Temps { get; set; }
        public Nullable<decimal> clt_ID { get; set; }
        public Nullable<decimal> fact_V_R_O_Montant { get; set; }
        public Nullable<decimal> fact_V_R_O_Remise { get; set; }
        public Nullable<decimal> fact_V_R_O_Total { get; set; }
        public Nullable<decimal> fact_V_R_O_Net { get; set; }
        public Nullable<decimal> dvs_ID { get; set; }
        public Nullable<decimal> fact_V_R_ID { get; set; }
        public Nullable<decimal> barn_ID { get; set; }
        public Nullable<bool> fact_V_R_O_Status { get; set; }
        public string fact_V_R_O_Note { get; set; }
    
        public virtual Branche Branche { get; set; }
        public virtual Client Client { get; set; }
        public virtual Devise Devise { get; set; }
        public virtual Facture_Vente_Retour Facture_Vente_Retour { get; set; }
    }
}
