//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Bon_Sortie_Magasin
    {
        public decimal bon_S_Mags_ID { get; set; }
        public string bon_S_Mags_Code { get; set; }
        public Nullable<System.DateTime> bon_S_Mags_Date { get; set; }
        public Nullable<System.TimeSpan> bon_S_Mags_Temps { get; set; }
        public string bon_S_Mags_Text { get; set; }
        public Nullable<bool> bon_S_Mags_Status { get; set; }
        public Nullable<decimal> bons_ID { get; set; }
        public Nullable<decimal> bon_T_ID { get; set; }
    
        public virtual Bon_Type Bon_Type { get; set; }
    }
}
