//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation_Caisse
    {
        public decimal cais_O_ID { get; set; }
        public string cais_O_Code { get; set; }
        public string cais_O_Nom { get; set; }
        public Nullable<System.DateTime> cais_O_Date { get; set; }
        public Nullable<System.TimeSpan> cais_O_Temps { get; set; }
        public Nullable<decimal> cais_O_Montant { get; set; }
        public Nullable<decimal> cais_O_Total { get; set; }
        public Nullable<bool> cais_O_Type { get; set; }
        public Nullable<int> cais_O_Status { get; set; }
        public string cais_O_Note { get; set; }
        public Nullable<decimal> ban_C_ID { get; set; }
        public Nullable<decimal> esp_C_ID { get; set; }
        public Nullable<decimal> cais_ID { get; set; }
    
        public virtual Compte_Bancaire Compte_Bancaire { get; set; }
        public virtual Compte_Espece Compte_Espece { get; set; }
        public virtual Main_Caisse Main_Caisse { get; set; }
    }
}
