//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit_Barcode
    {
        public decimal brdc_ID { get; set; }
        public string brdc_Code { get; set; }
        public string brdc_Numero { get; set; }
        public string brdc_Type { get; set; }
        public Nullable<bool> brdc_Status { get; set; }
        public string brdc_Note { get; set; }
        public Nullable<decimal> prd_ID { get; set; }
    
        public virtual Produit Produit { get; set; }
    }
}
