//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesDB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unite_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unite_Type()
        {
            this.Facture_Achat_Bonus = new HashSet<Facture_Achat_Bonus>();
            this.Facture_Achat_Produit = new HashSet<Facture_Achat_Produit>();
            this.Facture_Achat_Produit_Retour = new HashSet<Facture_Achat_Produit_Retour>();
            this.Facture_Vente_Bonus = new HashSet<Facture_Vente_Bonus>();
            this.Facture_Vente_Produit = new HashSet<Facture_Vente_Produit>();
            this.Facture_Vente_Produit_Retour = new HashSet<Facture_Vente_Produit_Retour>();
        }
    
        public decimal unt_T_ID { get; set; }
        public string unt_T_Code { get; set; }
        public string unt_T_Nom { get; set; }
        public string unt_T_Type { get; set; }
        public Nullable<bool> unt_T_Status { get; set; }
        public string unt_T_Note { get; set; }
        public Nullable<decimal> unt_M_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Bonus> Facture_Achat_Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Produit> Facture_Achat_Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Achat_Produit_Retour> Facture_Achat_Produit_Retour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Bonus> Facture_Vente_Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Produit> Facture_Vente_Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture_Vente_Produit_Retour> Facture_Vente_Produit_Retour { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
    }
}
